AllCops:
  Include:
    - '**/Rakefile'
    - '**/Gemfile'
    - '**/*.gemspec'
  Exclude:
    - 'bin/*'
Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Enabled: false

Metrics/LineLength:
  Max: 120

Style/MultilineOperationIndentation:
  EnforcedStyle: indented
